MISE_EXEC_PREFIX = 'mise exec --'

namespace :env do
  desc 'Init env'
  task :init do
    if File.exist?('.mise.toml')
      install_mise
      puts "mise installed: #{`mise --version`}"
      sh "mise install"
    end
    
    if File.exist?('.pre-commit-config.yaml')
      Rake::Task['env:githook'].invoke
    end
  end

  desc 'Install git hook'
  task :githook do
    sh "#{MISE_EXEC_PREFIX} pre-commit install"
  end

  desc 'Update swift-style-guide'
  task :update_style_plugin do
    sh "mise plugin uninstall swift-style-guide"
    sh "mise uninstall swift-style-guide"
    sh "mise install"
  end

  def install_mise
    output = `which mise >/dev/null 2>&1`
    if $?.success?
      return
    end

    puts "mise not found, installing..."
    sh "curl https://mise.run | sh"

    case ENV['SHELL']
    when /bash/
      sh 'echo "eval \"\$(~/.local/bin/mise activate bash)\"" >> ~/.bashrc'
      sh "source ~/.bashrc"

    when /zsh/
      sh 'echo "eval \"\$(~/.local/bin/mise activate zsh)\"" >> ~/.zshrc'
      sh "zsh -c 'source ~/.zshrc'"

    else
      puts "Unknown shell env!"
      exit 1
    end
  end
end

namespace :swift do
  SWIFTFORMAT_COMMAND = 'swiftformat . --config ./swift/Sources/rakuyo.swiftformat'
  SWIFTFORMAT_LINT_COMMAND = 'swiftformat . --config ./swift/Sources/rakuyo.swiftformat --lint'

  desc 'Run SwiftFormat without Mise'
  task :format_without_mise do
    sh SWIFTFORMAT_COMMAND
  end

  desc 'Run SwiftFormat'
  task :format do
    sh "#{MISE_EXEC_PREFIX} #{SWIFTFORMAT_COMMAND}"
  end

  desc 'Run SwiftFormat Lint without Mise'
  task :lint_without_mise do
    sh SWIFTFORMAT_LINT_COMMAND
  end

  desc 'Run SwiftFormat Lint'
  task :lint do
    sh "#{MISE_EXEC_PREFIX} #{SWIFTFORMAT_LINT_COMMAND}"
  end
end
